// รูปสำหรับปุ่มทดสอบ (/test) — PNG ไล่สีฟ้ามีกรอบเข้ม ขนาด 600x400 ประมาณ 2.8 KB
// ฝังไว้ในโค้ดเพื่อให้ทดสอบส่งเข้า LINE ได้โดยไม่ต้องพึ่งไฟล์ภายนอกหรือ Shortcut

const TEST_IMAGE_BASE64 =
  'iVBORw0KGgoAAAANSUhEUgAAAlgAAAGQCAIAAAD9V4nPAAAK8klEQVR42u3V5XIghmFG0fzvg5SZU2ZmZkrbpCk3ZrZjdmzH' +
  'ENsxO2Zmppgd2zEJVlrBimGlXUkraTEzfYpP87U5M+cJ7p/7iW/55GcB4JvWJyQAwAgBwAgBwAgBwAgBwAgBwAgBwAgBwAgB' +
  'wAgBwAgBwAgBwAgBwAgBwAgB4JtkhN/6uY8BoFZ8hN923McAUCs+wm8/bgAAahkhAEaYHOF3HD8AALWMEAAjTI7wO48fAIBa' +
  '+RGeMAAAteIj/K4TBgCgVnyE333iAADUMkIAjDA5wu85cRAAauVHeNIgANSKj/B7TxoEgFpGCIARJkf4fScPAkAtIwTACJMj' +
  '/P6TBwGgVnyEP3DKIADUMkIAjDA5wh88ZQgAauVHeOoQANSKj/CHTh0CgFr5EZ42BAC14iP84dOGAKBWfIQ/ctoQANTKj/D0' +
  'IQCoFR/hj54+BAC1jBAAI0yO8MfOGAaAWkYIgBEmR/jjZwwDQK38CM8cBoBa8RF+8sxhAKgVH+FPnDUMALWMEAAjTI7wJ88a' +
  'BoBa+RGePQwAteIj/KmzdwFALSMEwAiTI/zpc3YBQK34CH/mnF0AUMsIATDC5Ah/9vO7AKCWEQJghMkR/ty5uwCglhECYITJ' +
  'Ef78uSMAUCs/wvNGAKBWfIS/cN4IANSKj/AXzxsBgFr5EZ4/AgC14iP8pfNHAKCWEQJghMkR/vIFIwBQawdGOAoAteIj/JUL' +
  'RgGgVn6EF44CQK34CH/1wlEAqBUf4a9dNAoAtYwQACNMjvDXLxoFgFr5EV48CgC14iP8jYtHAaDWDoxwNwDUio/wNy/ZDQC1' +
  '4iP8rUt2A0AtIwTACJMj/O0v7AaAWkYIgBEmR/g7l+4GgFpGCIARJkf4u5fuBoBa+RFeNgYAteIj/L3LxgCgVnyEv3/ZGADU' +
  'yo/w8jEAqBUf4R9cPgYAtYwQACNMjvAPvzgGALWMEAAjTI7wj64YA4Ba8RH+8RXjAFDLCAEwwuQI/+TKcQCoZYQAGGFyhH96' +
  '5TgA1MqP8KpxAKgVH+GfXTUOALWMEAAjTI7wz68eB4Ba8RH+xdUTAFDLCAEwwuQI//JLEwBQywgBMMLkCP/qmgkAqGWEABhh' +
  'coR/fc0EANSKj/Bvrp0AgFpGCIARJkf4t9dOAkCt/AivmwSAWvER/t11kwBQywgBMMLkCP/+y5MAUMsIATDC5Aj/4fpJAKgV' +
  'H+Gnrp8EgFpGCIARJkf4jzfsAYBaRgiAESZH+E837AGAWvkR3rgHAGrFR/jPN+4BgFpGCIARJkf46Zv2AECt+Ag/c9MeAKiV' +
  'H+HNUwBQKz7Cf7l5CgBqGSEARpgc4WdvmQKAWkYIgBEmR/ivt0wBQK34CP/t1ikAqGWEABhhcoT/fusUANTKj/C2aQCoFR/h' +
  'f9w2DQC1jBAAI0yO8D+/Mg0AtYwQACNMjvC/bp8GgFrxEf737dMAUMsIATDC5Aj/545pAKi1AyOcAYBa8RF+7o4ZAKiVH+Gd' +
  'MwBQKz7C4+6cAYBa8REef+cMANTKj/CuGQCoFR/hCXfNAECt/AjvngGAWvERnnj3DADU2oERzgJArfgIT7pnFgBqGSEARpgc' +
  '4cn3zAJArfgIT7l3FgBqGSEARpgc4an3zgJArfwI75sFgFrxEZ523ywA1NqBEc4BQK34CE+/fw4AasVHeMb9cwBQKz/CB+YA' +
  'oFZ8hGc+MAcAtYwQACNMjvCsB+cAoJYRAmCEyRGe/eAcANTKj/CheQCoFR/hOQ/NA0Ct+Ag//9A8ANTKj/DheQCoFR/huQ/P' +
  'A0Ct/AgfmQeAWvERnvfIPADUMkIAjDA5wvMfnQeAWjswwgUAqBUf4QWPLgBArfgIL3xsAQBqGSEARpgc4UWPLQBArfwIH18A' +
  'gFrxEV78+AIA1MqP8IkFAKgVH+ElTywAQK34CL/wxCIA1MqP8MlFAKgVH+GlTy4CQC0jBMAIkyO87KlFAKhlhAAYYXKElz+1' +
  'CAC18iN8ehEAasVH+MWnlwCgVnyEVzy9BAC18iN8ZgkAasVHeOUzSwBQKz/CZ5cAoFZ8hFc9uwQAtYwQACNMjvDq55YAoFZ8' +
  'hF96bgkAau3ACJcBoFZ8hNc8vwwAtYwQACNMjvDa55cBoFZ+hC8sA0Ct+Aive2EZAGrlR/jiMgDUio/wyy8uA0Ct+Aivf3EZ' +
  'AGrlR/jSXgCoFR/hDS/tBYBaRgiAESZHeOPLewGglhECYITJEd708l4AqBUf4c1f3QsAtYwQACNMjvCWV/YCQK0dGOEKANSK' +
  'j/DWV1YAoFZ+hK+uAECt+Ahve3UFAGoZIQBGmBzhV15bAYBa8RHe/toKANQyQgCMMDnCO15fAYBaOzDCVQCoFR/hna+vAkCt' +
  '/AjfWAWAWvER3vXGKgDUyo/wzVUAqBUf4d1vrgJArfgI73lzFQBq5Uf41ioA1IqP8N63VgGg1g6McB8A1IqP8L639wFALSME' +
  'wAiTI7z/7X0AUCs+wge+tg8AahkhAEaYHOGD7+wDgFpGCIARJkf40Dv7AKBWfoTv7geAWvERPvzufgCoZYQAGGFyhI+8tx8A' +
  'asVH+Oh7+wGglhECYITJET729f0AUMsIATDC5Agff38NAGoZIQBGmBzhE++vAUCt+Aif/GANAGoZIQBGmBzhUx+sAUCt/Ag/' +
  'XAOAWvERPv3hGgDUMkIAjDA5wmc+WgeAWkYIgBEmR/jsR+sAUCs+wuc+XgeAWkYIgBEmR/j8wDoA1DJCAIwwOcIXBtYBoFZ+' +
  'hIPrAFArPsIXBzcAoFZ8hC8NbgBArfwIhzYAoFZ8hC8PbQBALSMEwAiTI/zq8AYA1DJCAIwwOcJXdm0AQC0jBMAIkyN8ddcB' +
  'AKgVH+FrIwcAoJYRAmCEyRG+PnIAAGrlRzh6AABqxUf4xugBAKhlhAAYYXKEb+4+AAC1jBAAI0yO8K3dmwBQKz7Ct8c2AaCW' +
  'EQJghMkRfm18EwBqGSEARpgc4TvjmwBQKz/CiU0AqBUf4bsTmwBQKz7C9yY2AaBWfoSTWwBQKz7Cr09uAUAtIwTACJMjfH/P' +
  'FgDUMkIAjDA5wg+mtgCglhECYITJEX44tQUAteIj/Gh6CwBq7cAItwGgVnyEH09vA0Ct/AhntgGgVnyEAzPbAFDLCAEwwuQI' +
  'B2e3AaBWfIRDs9sAUCs/wrltAKgVH+Hw3DYA1NqBER4EgFrxEe6aPwgAtYwQACNMjnBk/iAA1MqPcOEgANSKj3B04SAA1IqP' +
  'cPfCQQColR/h4kEAqBUf4djiIQCoZYQAGGFyhONLhwCglhECYITJEU4sHwKAWvERTi4fAoBaRgiAESZHuGfvIQCoZYQAGGFy' +
  'hFN7DwNArfwIVw4DQK34CKdXDgNALSMEwAiTI5xZPQwAteIjnF09DAC18iPcdxgAasVHOLfvMADUMkIAjDA5wvn9RwCglhEC' +
  'YITJES7sPwIAtfIjXDsCALXiI1xcOwIAteIjXFo7AgC18iNcPwIAteIjXF4/AgC18iPcOAIAteIj3LtxFABqGSEARpgc4cqB' +
  'owBQKz7C1QNHAaCWEQJghMkR7ts8CgC1jBAAI0yOcP/mUQColR/h1lEAqBUf4drWMQCoZYQAGGFyhOvbxwCgVnyEG9vHAKBW' +
  'foQHjwFArfgIDxw8BgC1jBAAI0yOcPPQMQCoZYQAGGFyhFuHvgEAteIj3D78DQCoFR8hAPx/YoQAGCEAGCEAGCEAGCEAGCEA' +
  'GCEAGCEAGCEAGCEAGCEAGCEAGCEAGCEAGCEA/B/1v2kcLpUxfCg1AAAAAElFTkSuQmCC';

/** คืนรูปทดสอบเป็น Uint8Array */
export function testImageBytes() {
  const binary = atob(TEST_IMAGE_BASE64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}
